version: '3.8'

services:
  auth-proxy:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - auth-network

  auth-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: supertokens
    expose:
      - "5432"
    networks:
      - auth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "supertokens"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - auth

  supertokens-core:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.3.0
    depends_on:
      auth-db:
        condition: service_healthy
    expose:
      - "3567"
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://admin:admin@auth-db:5432/supertokens"
      SUPERTOKENS_DATA_DIR: /app/data
    volumes:
      - supertokens-data:/app/data
    networks:
      - auth-network
    profiles:
      - auth
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  auth-network:
    driver: bridge

volumes:
  postgres-data:
  supertokens-data:
